export enum UserStatus {
  STAGED = 'STAGED',
  PROVISIONED = 'PROVISIONED',
  ACTIVE = 'ACTIVE',
  RECOVERY = 'RECOVERY',
  PASSWORD_EXPIRED = 'PASSWORD_EXPIRED',
  LOCKED_OUT = 'LOCKED_OUT',
  DEPROVISIONED = 'DEPROVISIONED',
  SUSPENDED = 'SUSPENDED',
}
