-- Dark Knight: Rises reviews
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('2c89c884-c0e2-46d3-97aa-4b5e0d1ce6cb', 10, 'I love this director!!!', 'WhoAmI@cs.khpi.edu.ua', '303e7f44-4606-4848-ab3c-b8ba767ea526',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('dcf795b2-813c-449b-924f-fd7705c71a26', 10, 'The Dark Knight Rises is the taut and satisfying finale to a beastly franchise that not only proposed new interpretations of a beloved tale, but it also re-engineered what we imagine a superhero movie to be.', 'Ryan Gilbey', '303e7f44-4606-4848-ab3c-b8ba767ea526',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('892a6e88-d751-4fef-a02f-9f3b24fdd25a', 10, 'Nolan somehow never loses control - this is an accomplished and tremendously confident filmmaker, both in the execution of his thrilling chases and action beats, and in his manipulation of the complicated, multi-faceted narrative.', 'Candice Frederick', '303e7f44-4606-4848-ab3c-b8ba767ea526',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('4d9d6b34-ba1b-4a6d-999a-2bd4af32d2af', 6, 'I respected The Dark Knight Rises; I didn`t quite love it.', 'Jenny McCartney', '303e7f44-4606-4848-ab3c-b8ba767ea526',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('072fa20f-a2de-44d5-9286-d3c9a8f037c0', 7, 'A very nice follow up to the Oscar winning "Dark Knight" "The Dark Knight Rises" dosnt disappoint. With more vehicles and some better acting by Bale this movie is mostly carried by its fantastic story and its crazy villain Bane. Once again Nolan outdoes himself in this beautiful crime thriller piece. The RT score is perfect where it is but id like to see it reach a 90% or higher.', 'Cory Woodroof', '303e7f44-4606-4848-ab3c-b8ba767ea526',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('19611292-89a0-4d4d-8726-bf07a62b3c86', 9, 'While falling flat at some points, The Dark Knight Rises is a thought-provoking, thrilling action film that has some of the most beautiful IMAX film sequences ever captured. It concludes Nolan`s ambitious tale with one of the best trilogy endings ever.', 'Sean Axmaker', '303e7f44-4606-4848-ab3c-b8ba767ea526',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('04ac68f4-1fbc-45a1-89f7-e61a8cb8906a', 10, 'Although it will have to sit in the shadow of The Dark Knight. This film had amazing action Sequences and Tom Hardys portrayal as Bane has redeemed the villain since Banes appearance in that horrible Batman Movie Batman and Robin. I’m Grateful for this film but I’m sad it was the last one', 'James Croo', '303e7f44-4606-4848-ab3c-b8ba767ea526',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('41e3cc49-63f4-491f-aab5-19188fd512e4', 8, 'A very solid conclusion to Nolan`s Dark Knight trilogy. Ledger`s Joker performance puts the Dark Knight ahead of this one for greatness... and Hardy`s Bane voice is silly and distracting, so that`s a strike against it... but, again, the script, directing, score and cast are all fantastic (including some nice additions like Joseph Gordon Levitt, Matthew Modine and Anne Hathaway).', 'Keith Garlington', '303e7f44-4606-4848-ab3c-b8ba767ea526',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));

-- The Lord of The Rings reviews
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('9b2d4ab4-2ffc-40f8-aefa-f7d16df42391', 10, 'All the threads of Tolkien`s magnum opus come together in the most elegant of fashions in the final part of Peter Jackson`s adaptation. Humanity makes a last stand at Minas Tirith, the Hobbits travel through Mordor, our heroes try to by time for Frodo to complete his mission and the Evil Sauron gets tired of the whole game and lashes out with all his might and fury.

"Return of the King" is 4 hours of payoff, a third act in a gigantic epic rather than a mere film of its own. As such it is intensely dramatic and dynamic and you can very much sense that though peter Jackson spared no effort on the previous episodes, this is clearly his favorite. the film floats by at a thunderous pace, taking us through unforgettable moments such as the battle of Minas Tirith itself, a marvel of seamless animation and epic film-making, it demands to be seen, as it has too many jaw-dropping moments to choose from. The quieter character moments keep gaining in potency and the full weight of the stakes and their heartbreaking consequences is never in doubt.

The cast of these films have played their parts to perfection and again Jackson deserves overall credit for choosing actors that so perfectly match Tlolkien`s creations: Ian McKellen and Christopher Lee are their own usually excellent selves, and the hobbits remain endearing, but of all the uniformly great cast, the true standouts are Viggo Mortensen and David Wenham as the tragic Faramir, whose relationship with his brutish father is the most traumatic of the film. Jackson pushes them even further by having them sing at a few key moments (a practice employed to powerful effect by Tolkien in the books), a daring undertaking that works wonders. And though he may offer one ending too many, he does have the decency to show off each surviving character with the appropriate screen time and respect.

Now that the trilogy is complete, it can be viewed as one big film, as it should be. After 8 years, Jackson has done the impossible: he has taken Tolkien`s huge legend and made films that stand on their own and have revolutionized film-making, setting the new benchmark for cinematic epics. Changes have been made to Tolkien`s source novels, but they make for better, more fluid films, more faithful in spirit to Tolkien`s myth than anyone had the right to hope for.

A masterpiece, whether as part of a bigger whole or on its own. Well deserving of all the high praise thrown at it, and then some...', 'OttoVonB', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('815af5b5-642a-4a96-91d0-f2c2fee14d16', 10, 'Wonderful on every level. Love the characters and special effects. One of the biggest, most massive battle scenes ever put on the silver screen. A great end to a monumental epic.', 'MrHeraclius', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('86e6062a-b9e7-43a6-b656-d4a023369ce2', 9, 'Frodo and Sam continue their quest to destroy the ring, led by the untrustworthy Gollum. Meanwhile the rest of the Fellowship prepare for another battle to hold a human city against an onslaught of orcs.

If you check my other reviews you will note that I wasn`t a massive fan of the first two films - I loved them, but was not blind to their faults. However, let me just lay my cards out here, I was totally blown away by this film. For the vast majority (and more of that later) the narrative flowed really well where the other two films had struggled to really keep consistent. Here the various strands work well together and, while characters have only brief times to tell stories, on the whole it manages it well. I got the feeling that the film really let rip - it knew this was the ending and it did feel that everything came together in a collection of noise and energy which really made it feel like the final part of a trilogy rather than just a stand alone film.

The one area where the film really stutters (and actually caused people to leave the cinema in annoying numbers) is ironically the place where Jackson is true to the book, and that`s the final 20 minutes. There is a clear scene where the film ends, however it then runs for another 20 minutes - which is a mix of scenes that all fade out like they were the end. To Joe Public (ie me!) I would have been happy not to have all the loose ends tied up in the way the book does it - the film should have ended on a high (with the King being crowned etc) but instead it seems to crawl to an end in a way that is not in line with the momentum of the film (if not the whole trilogy!) This problem is minor on the grand scheme of things, but I would rather have left the cinema on my high than be made to wonder `when`s this ending? Is this the end now? Oh, maybe this is it now?` - but I do understand why it was done this way.

The cast, as they have been all the way, are excellent. Wood`s Frodo changes well during this film while Astin is touching in his portrayal of unerring friendship. Bloom and Rhys-Davis had less to do but came into their own during the battle scenes - adding both action and the odd comic touch (`that still counts as one` being accepted by the audience as a chance to break the tension). Mortensen is the title character and serves it well, with McKellen also continuing his strong role. I could list through the whole cast but I will stick with noting two things. Firstly, both Monaghan and Boyd had bigger and more meaningful roles and rose to them well. Secondly I continue with my belief from the second film that Serkis is the stand out actor of the trilogy. His Gollum is so much more than an effect - he is tragic, fearsome, hateful and funny. Praise of course goes to the special effects for making this character tell so much with an expression but to pretend that the work of the actor is secondary to the character (as opposed the look) is foolish. He deserved one for Two Towers so I hope an Oscar goes his way. It was a shame to not have screen time for Lee but the film works well without him and it was a brave move by the editors.

The special effects do not stand out - and that`s a compliment. Even in state of the art movies of late I have been aware that I could be watching a video game. Here I only occasionally noticed that things were clear computer effects, even though the majority of the film was! This is how they SHOULD be used - not as a draw in their own right but as part of the film. Whether it be the massive battle scenes that are spectacular or the animated spider or just the fact that I forget that Gollum is only an effect, I cannot fault it`s use of effects or the sheer visual feast that is this film.

I have tried not to gush because there will be plenty of others to do that without me joining them, but it is hard to really fault this film. It is the strongest of the trilogy and brings it all together really well, it is an emotional event more than a film and, if Jackson needs 20 minutes of slow closure to finish it to his satisfaction then I can give him that in return for all the hours of wonderful cinema that he has given me.
', 'WhoAmI@mail.com', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('80bab217-aa3f-46eb-9cb6-1f56748712fa', 9, 'I treat all three instalments of the Lord of the Rings trilogy as one film, because that`s how they play. The sense of adventure and the enormity of the story is something that no other film has ever done.', 'ROB', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('acc8eea3-3751-4b56-9249-353181dd0ef2', 10, 'This is the defining movie of Peter Jackson`s career. Though it strayed quite far from the book at times, it worked the miracle of remaining true to the book`s spirit and not striving for the random flamboyance that the Hobbit films today fall to.', 'AdrianV', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('aa6828b7-531e-470b-b588-fe0f50757d6c', 10, 'Everything but the acting was perfect. Not, the acting wasn`t bad it was a bit more than ok even. Yes, i agree with that, and everyone who didn`t liked the series, but that isn`t the point! it`s a fabulos story told perfect it` doesn`t need even more exagerations from the actors to ruin it. it was acted as it should have been. Few movies ever made me cry this made me more than cry at the end', 'Jake', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('bbde65fa-073b-46aa-81e4-b3297904108a', 10, 'First you complain about the first two movies not wrapping up the story.....now you complain about the complete opposite. I watched the extended version of this film and was actually surprised that it was 250 minutes long. Seemed like a lot less. Anyone who`s read this book should agree that if Peter Jackson had ended it the same way tolkein did it the climax would have come at the hour-and-a-half mark, with 3 more hours to go, which is fine for a book which is read in multiple sittings but tourture for a movie. I`m glad Jackson ended it like he did and wrapped everything up. Well done sir!', 'Jogn Doe', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('9870d76a-96f5-49bc-ab72-e4f2da412fee', 10, 'I love this movie so very much. Every time i see it, it still tears me up after watching it at least 9 times. Even though it is really hard to tell what there saying( another marvelous feet by the director). An incredible movie that i think has the best freaking ending ever', 'Stan Hmm', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('96320cb2-ba79-4793-a66e-c4a49d2ab792', 10, 'The best film I`ve ever watched. It combines everything I love about films. Superb directing, passionate acting (with the exception of Bloom), amazing music, and the ability to grab and not let go. This film (and trilogy) completely fulfill the definition of epic.', 'Andromeda Finski', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('aab56743-fe2a-46a6-b300-9b7f6723bc42', 9, 'For Jackson to shoot The Lord of the Rings with a local crew in New Zealand, a country at the edge of the world with little stake in its doings, is a marvel which may only be repeated by Jackson himself. Apart from the international cast, the people who were actually working to bring us the trilogy, like special effects, were Kiwis. The majority of this credit must go to Jackson for his leadership and vision, and for succeeding in hiring an able team.

The Return of the King is the concluding chapter in the trilogy. The story is picked up where it was left off at the end of The Two Towers. We are shown a glimpse into Gollum`s past. The rest of the fellowship reunite at Isengard. Saruman`s fate is omitted from the theatrical edition, which I always found odd given his importance in the previous instalment.

It is a time for festivities in Rohan in the wake of the victory at Helm`s Deep. An accident shows us Sauron`s plans for Minas Tirith, the legendary capital of Gondor. The fellowship breaks again in a different way. Gandalf rides to the city to find the steward reluctant to lift even a finger for its defence. Needless to say, things work out and Rohirrim ride for Gondor`s aid. Faramir, dejected by his father, rides out in a last ditched effort to reclaim Osgiliath.

A family heirloom is returned to Aragorn which he uses to find help in the most unexpected places. Another plot device if you ask me. If you keep an eye out for them, they become very obvious. Jackson could have lessened its impact or omitted it entirely, making sure the battle was won through the prowess of battle commanders, which he failed to do so. As Fellowship never purported to show us a huge battle at all, and did not have to resolve it, I will forever hold it in higher regard than Return. The Two Towers resolved its battle much more satisfactorily, but Return has got much more on the former in other areas, so the second place goes to the latter.

Orcs begin the attack on the city. Gandalf leads the defence. The battle looks grander than the one at Helm`s Deep, the besieging armies and weapons more awe-inspiring. The special effects used to bring this conflict to life were stunning_ showing the destruction of architecture by the catapults and the loss of men and Orcs; as well as bringing to life Shelob, the giant spider. The scene of the Rohirrim cutting through the Orcs on their horses is possibly the most spectacular. Oliphaunts and Nazguls join the fight.

My previous apathy for Eowyn is cured after watching the extended version, in which she develops significantly. In fact, she is the only female character in Middle Earth who is of some worth, and I like where her story took us, climaxing in a very satisfactory way in the middle of a battle, pitted against only the most important antagonists.

The main trio_ Aragorn, Legolas and Gimli, are absent from much of the fighting, as the other two accompany the former on his journey of self-discovery. I was earnestly hoping for them to join the fight, which they did (Legolas displaying some very impressive killer moves), but it was so ridiculously short. Four minutes. Believe me, I counted. In this regard The Two Towers was much better, as well as having more memorable scenes with the Gollum.

Frodo`s inevitable clash with Gollum goes full circle. Sam displays unprecedented strength of character and resolve, and the Hobbits thrive without much help from men. Men ride once more to aid Frodo in his quest to rid them of the ring, and a final battle sequence follows, after which it is destroyed. In epilogue, we learn about the fates of the Hobbits, Aragorn and Gandalf.

The extended edition had some interesting scenes which enriched the characters and the story, but also some which betrayed some ineptitude at editing. One scene had a character utter the exact same dialogue to persuade someone in the span of a single conversation. Surely a rewording would have been more effective. I scoffed at a particular attempt to blossom an affair between two secondary characters. Such things should have been hinted at in the epilogue. No one is interested in that stuff when the stakes involve the end of the world.

Finally, a discussion about the extraordinary tally at the Oscars. Eleven well-deserved wins out of as many nominations, in fields as diverse as art direction, costume design, make-up, sound, original score, original song, editing, visual effects, adapted screenplay, directing, and Best Picture.

In the end I would observe that the extended editions of the first and second instalments, three hours twenty and three hours thirty-three minutes respectively, enhanced the tales while the third one, a crushing four hours, did not achieve anything of worth', 'AndrrrSparrow', '2073d25d-bf80-46d0-9c20-da96dd8cbaad',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));


INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('401ce058-c187-4708-bfac-ed2de3882c4b', 10, 'If there was a minor quibble with the movie, it is that it is a little overlong. Putting that aside, this is a truly wonderful film, that is definitely one of the highlights of 2003. The whole film is a wonder to look at, with splendid costumes and very realistic sets. The script is just a gem, with classic and original lines like "Stop blowing holes in my ship," that sometimes have you in gales of laughter. I did find the pirates as skeletons quite frightening though. Films that have scared me are The Mummy and Pitch Black. The performances were first-rate, especially Johnny Depp in possibly his best performance. His character Jack Sparrow is a somewhat charming, likable rogue, and Depp pulled him off to perfection. As Barbossa, Geoffrey Rush positively sinks his teeth into his role, sometimes sinister and sometimes fun. Kiera Knightly proves once again that she looks lovely in period dramas, because it really does suit her. Orlando Bloom is dashing as Will Turner. Before I round off, I want to mention another aspect of the film, the music by Hans Zimmer(Lion King)... it was outstanding! Zimmer should be up there with the great film composers, like James Horner(American Tail, Titanic), John Williams(ET, Home Alone) and the late Jerry Goldsmith.(Legend, The Shadow) All in all, a highly entertaining film! 10/10 Bethany Cox.', 'Brad2002', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('5b5899c8-9f48-4951-82a6-65c9547c9eb5', 8, 'Although I had expectations ( from watching the trailers ) that this might be a good movie, I was still surprised that it`s as good as it is. The story is actually more complex than I had expected, involving cursed pirates and their quest to rid themselves of the curse. I won`t say more than that so as not to spoil it if you haven`t seen it.

There aren`t as many action scenes as I had thought there would be in a pirate movie, but the ones that are in the movie were very fun and enjoyable. After seeing it, I think it had the right balance of action and drama. There are also, of course, a lot of funny bits interspersed between the action and drama. Some really good special effects also add to the enjoyment of this movie.

I wasn`t much of a fan of Johnny Depp until I saw this movie. I think he deserved to win the Academy Award for best actor. It`s largely because of his performance, IMO, that the movie was so good. Most of the supporting cast did well, mind you, just that Johnny Depp stood high above the rest. I did find Orlando Bloom`s performance a bit wooden, but other than that the acting was good.

Basically, it`s a really fun movie and I`d give it about 8 out of 10', 'ForceofSU', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('c32290be-435c-4bf3-ae62-047989520d33', 10, '"Even I love Johnny Depp, and I`m male," a previous reviewer declares, tongue in cheek. Well, I wouldn`t go quite that far, but there`s no doubt whatsoever that when I lost my heart to this film, Johnny Depp`s outrageous Cap`n Jack Sparrow had almost everything to do with it. I don`t normally review `current` films, so the very fact that I`m writing this highlights an almost unprecedented event - after endless failures, Hollywood has finally rediscovered the spirit of the classic swashbuckler movie.

With hindsight, I think the one brilliant decision that was made at some point - given a modern production environment - was to *separate the roles* of hero and swashbuckler. You can then have your worthy Costner-type juvenile lead, as required, who has to Come To Terms with his Past (although his eventual fate is a trifle unexpected in conventional terms...) - *but* you can also have your essential and irrepressible swaggering rogue (of course, he totally steals the film from the moment he first appears, but *that`s* no hardship!)

The moonlight special effects were overdone, in my opinion - not that they aren`t believable, but that they would have been more effective if used more sparingly, for occasional flashes of nastiness rather than solid minutes of battle. However, that`s a minor niggle. The stunts are energetic, highly satisfactory, *not* computerised, and on occasion even carried out by the stars :-)

The other saving grace of the production is its humour - not that there aren`t a few over-arch knowing references, but on the whole it manages to send itself up without suspending disbelief in the process. Jack Sparrow`s first arrival on the scene (with total aplomb aboard a steadily-sinking boat) is a prime example, as indeed are the vast majority of subsequent scenes involving this character...

The basic Romance and Rescue structure is satisfactory enough, with the addition of the requisite Feisty Female for the 21st century (though I felt the character would have been a little more historically plausible if she had been a little less liberated - she clearly possesses a stronger character than her young man, she doesn`t have to strive to be his physical equal as well...) However, it is the pirates themselves who really make the film, simply by being a pack of unreconstructed and uninhibited villains (from the Jeffrey Farnol School of Historical Dialect) who are far larger than life and totally unselfconscious about it. To quote the opening words of the `Guardian` review: "we have been waiting [50 years] for a modern pirate film featuring someone who, in all seriousness, actually says the words, or perhaps the two-syllable single word: `Ah-harrrrr!`"

Jack Sparrow, as swashbuckler extraordinaire and consummate rogue (of course, totally honest in his own way... ahem) is the main attraction of the entire film. Not so much loopy as totally round the bend - outrageous and unpredictable (there is a running gag throughout the first part of the film where he is repeatedly described as "the worst pirate I`ve ever seen", as in "the worst at it", only for the preposterous tactics in question to prove spectacularly successful).

This character saves the hero in more ways than one - without him, the film would be another "Mask of Zorro", a rather stodgy attempt to update an old favourite for modern-day sensibilities and compensate with more and flashier sword-fighting (swashbuckling is not *about* fighting! It comes into it, yes, but it`s not the point.) But together, the pair work off one another beautifully - reliability and inspired lunacy, self-doubt and cocky flamboyance, dogged devotion and shameless self-interest. The only question is which, precisely, is the sidekick...

There are two beginnings to this film, neither of them bearing any relation to the wooden costume-drama-by-numbers prologue that actually opens the movie. The moment when events start to move (it could scarcely be less subtle) is signalled by the swell of the theme music for the first time at Sparrow`s initial appearance. But for me the moment when the film really took off was in that instant during his first escape, when he seizes the rope and swings up, up, and out, in a classic swashbuckler move from the past that brought it all flooding back... and my heart flew up after him into my throat, and remained enjoyably in that position until the end of the movie, when the audience began spontaneously to applaud.

The film is far from perfect - characters like Captain Norrington (*please* - `Commodore`, like `Prime Minister`, is a job description, not a form of address!) and the Governor are little more than pantomime stereotypes, with only frustrating hints of humanity to indicate that they do after all have potential denied them by the script. Annoying anachronisms slip in - "it`s okay", "I was rooting for you" - most of the nautical jargon comes out with about as much sign of comprehension as a phonetic rendition of a foreign language, and Sparrow`s one precious charge of powder gets soaked through often enough in the course of the plot to be utterly useless by the end. Both hero and heroine come across as wooden and thankless roles. Orlando Bloom may be costumed to look increasingly like Errol Flynn during the course of the film (was it my imagination, or does he spend it gradually cultivating a duplicate of that famous moustache?), but, alas, any resemblance ends there.

But then it doesn`t really matter. It is Depp, not Bloom, who has inherited the mantle of Flynn and Fairbanks in this film. Jack Sparrow was the character who caught my imagination - and, since I`m extremely impressionable, also had a distinctly peculiar effect on the way I stood and walked for several hours later. And there`s not many films can say *that*..', 'Johnny Depp', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('800eb4dd-964b-4315-bd1b-abf890125f85', 10, 'And he has a great entrance. A really great one, if you haven`t seen it yet, go watch it! Even if it`s only the first scene with Johnny Depp as Cpt. Jack Sparrow! While many/some have dismissed Johnnys performance here as being gay, I do think his intentions were others! That`s not only because he himself said so in an interview (his inspiration being Keith Richards as he said), but also because I saw him as crazy, but genius guy, who was different.

But kudos have also to go out to Gore Verbinsky. First of all, for resurrecting the pirate movie "genre" (maybe genre is not the right word, but you get what I mean) and also for sticking to Johnnys decision to play Sparrow the way he did! It`s know that the studio didn`t want Johnny to play it like that. They were afraid, that Johnny`s performance would destroy it at the box office ... quite the opposite happened! Captain Jack Sparrow is the one who saved this thing from drowning (excuse the pun)! If you haven`t watched it yet, go out and see it now! A great adventure with a crazy/great guy in the middle of it!', 'Leo Di', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('faf126e3-fc64-4784-8818-1d2756290fc6', 7, 'This film is the epitome of a solid action-filled adventure. It has a straightforward and fast-paced plot that drags you in, propelled by a charming lead, witty jokes and compelling special effects. It roars along with gusto and thrills the audience from beginning to end.', 'Amber Sret', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('9e23584b-6fd6-4506-81b2-36b5f57743af', 10, ' just forgot how many times I watched this film.This film has comedy,adventure,action.The climax was awesome.A must watch movie.', 'Luke Sky', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('b51342ed-c66b-4824-9ad5-674125da7fa8', 9, 'Beautiful costumes..amazing story and concept and Johnny depp is simply amazing as captain jack sparrow. Must watch..its a combo of Action Mystery..Comedy and Adventure...', 'Korgi Mika', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('285fde35-354b-46c5-9527-f09921e9f98a', 9, 'There are two few action-adventure movies now a days that delivers such original characters, played by a truly incredible cast. When I first saw The Curse of the Black Pearl as a boy I was fascinated. There where Pirates, cannons, sword fights, treasures funny monkey`s and a beautiful girl, What more could you possibly ask for.

I can still remember when I saw Jack Sparrow for the first time. He may not of had the typical "hero" qualities that would see in somebody like say William Turner, but that is what made jack so undeniably brilliant, he wasn`t somebody we have experienced before. He was a witty, drunk, Sword fighting Pirate, with a flare for the dramatic. Seen for the first time in possibly the greatest hero entranced ever made. I glanced my stunned eye`s at the screen to behold the one they called Jack Sparrow, or should I say "Captain" Jack Sparrow. There he stood in all his glory, the anthem soundtrack blared as he stood on top of his wooden sinking ship, or boat... As he floats by the pirate outlaws hung by there necks, with a sign on them that states "pirates Ye Be Warned" he stops bailing his sinking boat in time to offer a kind salute, to his fellow dead pirates.

Its not long in till we are swept away by a amazing story of a two men desperately trying to find the loves of there life. One a Pirate after his stolen ship, and the other, a working hard blacksmith boy, trying to find his true love. Luckily for them, both loves have been taken by the "crew of the dammed". Barbossa, the fearless pirate with a pet monkey, yes a pet monkey. It soon becomes apparent that everyone in the story wants something, and they will screw and back-stab anyone who gets in there way, honestly this film there are know such thing as true friends, everyone will become an enemy in time.

After years of watching this film, it still reveals itself as nothing more but a great adventure movie, just plain fun. So why not give it ten out of ten. There is everything you want in an adventure movie, girls, fights and a little magic and mystery. Not to mention some of the best 1-liners you will ever hear, "you best start believing in ghost stories miss turner, you`re in one", and my personal favourite, the very last line in the film, as Jack prepares to embark on more of his adventures he quotes "bring me that horizon" as the ship sales off into the sunset.', 'Shadow Storm', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('55b9b19e-5810-4ff5-b41f-c2868c291d49', 9, 'I didn`t see this movie till it came out on DVD back 2 years ago.

I regretted not seeing it in theaters, because I kept thinking it`ll suck, because it didn`t look like it be anything similar to the ride at Disneyland.

But I was surprised to see that it`s a very well done action movie. And surprised that it`s even done by Disney. Cause it`s not the common Family Friendly movie you`d find from Disney.

The movie of course takes place in the Caribbean and during the 16th or 17th Century era. Which is when pirates ruled the 7 seas. A ship was sailing across the Atlantic which came across a wreckage of another ship. With only one passenger who is a young boy named Will Turner. Who had a gold medallion in his position. A girl named Elizabeth noticed the medallion to be pirate related so she took it and hid it from the ship`s crew so that way they wouldn`t think that Will is a pirate.

8 years later Elizabeth is more grown up and Will is a blacksmith who makes and repairs swords for the army of the seaport town of Cape Royal. Life was very calm and peaceful till Jack Sparrow came ashore of Cape Royal. He is not your average pirate and he`s very well known throughout the Caribbean. And there`s a lot more to his back story than there seem to be.

The medallion that Elizabeth holds is the key to breaking the curse of the pirates of the black pearl.

I gotta admit i did like it quite a bit. I just wish I knew it was going to be a must see movie. It had action, great special effects, plenty of humor in some parts, and great characters to know while watching the movie.

It`s also unlike the common pirate movies you`d see anywhere else. Which is because it`s a modern day made pirate movie. Those who are obsess with the ride might enjoy this movie a lot.', 'Shadow Kostya', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('d574f820-7b9f-4af4-8718-e741dad69d8f', 8, 'I very much enjoyed this movie the first time I saw it but lost interest on the second viewing, for some reason. It`s the usual Disney adventure story which means the same good and bad traits I usually find, namely:

THE GOOD - Nice camera-work and very slick-looking on DVD. Interesting characters, mostly here the ones played by Johnny Depp and Geoffrey Rush. It`s difficult to find a role in which Depp doesn`t play someone odd and/or fascinating. The story has a good mixture of drama, action, suspense and humor. Keira Knightley is attractive as the female lead and the story is interesting for the full 133 minutes (the last 10 minutes are ending credits.)

THE BAD - Once again, the messages are "laws are made to be broken;" "rebels in society are the good guys while authority figures are the villains," and the girl wants the poor man over the rich man, etc. etc. That all is so `60s clichéd by now, you`d think the Baby Boomers in Hollywood would grow up, but apparently not. These traits are in almost every film, including a worldly outlook on everything, which includes glorifying occult nonsense. Disney will never change.

OVERALL - A fun movie, thanks mainly to Depp, director Gore Verbnski and his cameramen, and successful enough to spawn a sequel.', 'Roberto Philipp', 'dba5a1bb-454e-484c-8695-48010c99a57a',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));


-- Home alone
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('b319c502-2251-41ee-bec9-f225d7f67682', 10, 'If you`re reading this in 2021, then you should know that it was exactly 31 years ago, in the month of November, that Home Alone was released in theaters. That striking fact alone is quite revealing, particularly because this film hasn`t "aged" at all and is still artistically and cinematically relevant even today.

There is very little I say about this absurdly entertaining film that likely hasn`t been thoroughly covered already. Home Alone is arguably the quintessential modern day holiday film that could only come from the exceptionally gifted mind of the late writer/director/producer, John Hughes. .

I purchased the Family Fun Edition DVD for the generous wealth of "extras" which include a camera interview with child star Macaulay Culkin, loads of deleted scenes, featurettes, a handful of games, and even a optional commentary track with the director, Chris Columbus, and the featured star, Macaulay Culkin.

As always, no spoilers here, but I will reveal that in "real life" co-star Daniel Stern has morbid arachnophobia (fear of spiders).', 'safenoe', '203c2490-f370-4684-a7cd-7290ceeddae0',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('834035b0-4f67-4f47-8894-aee6b37ac792', 7, 'In the Eighties, John Hughes churned out a handful of movies and scored many, many hits. Quite rightly, as most of them were seriously funny - I`m DEFINITELY not referring to Curly Sue, so relax! In one particular scene from Uncle Buck, Macaulay Culkin interrogates a babysitter through the letterbox to make sure she`s not a baddie. This inspired Hughes to write a whole new movie. Who would have known that this and its sequel would go on to become two of the biggest hits of all time? Both Hughes and Chris Columbus seem to prefer setting their movies during the holiday season (Gremlins, Planes, Trains & Automobiles, Christmas Vacation) and manage to pull them off without too much sentiment, or sickening amounts of gooey love.

There are two reasons why Home Alone was such a big success. The first is that it`s about a kid who outsmarts grown-ups, something that happens every day, only there`s a worldwide conspiracy of silence. This movie yells it out loud and clear. The second is John Williams`s magical score, which elevates the movie way above slapstick family fare to something more serious and regarded. It was nominated for an Academy Award, along with the Christmas carol Somewhere In My Memory, but lost to John Barry`s Dances with Wolves. Damn! In a mad rush to the airport one morning, the MacCallister family forget one little thing...Kevin (Culkin). He is an eight-year-old kid who wants nothing better than a peaceful Christmas and some time to himself. It`s hard for him to get this when living in a house with seven other people(the exact same house from Planes, Trains And Automobiles, don`t you know0. With the rest of the MacCallisters in Paris, Kevin runs wild doing whatever he wants, eating whatever he wants and watching whatever TV show he wants.

But there`s one major problem. The Wet Bandits, Harry (Joe Pesci) and Marv (Daniel Stern), are on the prowl and have knocked off every other house in Kevin`s street. His is next. And seeing that he`s man-of-the-house now, he HAS to defend it.

Using whatever tools are at his disposal (rusty nails, blow torches, Micro Machines) he sets up a labyrinth of booby traps, so that the Wets can`t break in. Their idiot-proof determination proves to be their downfall, as they are tortured and torn-up upon entering Kevin`s domain.

Although this is not the only point of the film, there is an important message that family is what really matters to a child, or to anyone, and having them home for the holidays is better than wandering a huge house all by yourself.

There are some movies that work best at Christmas and this is one of them. I`m not saying that in a couple of decades it will be the new It`s A Wonderful Life, but it will be remembered fondly at the very least.

Don`t be a Scrooge. It`s Christmastime. Go rush to check out Home Alone.', 'CuriosityKilledShawn14', '203c2490-f370-4684-a7cd-7290ceeddae0',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('a870b7dd-424a-4ffc-bd0c-321bf0a76197', 9, 'I absolutely love the first two Home Alone movies, the third one is adequate but the fourth movie is just dreadful and makes me vomit because of what it did to two underrated gems and a little -below-average follow up. Macaulay Culkin is wonderful as Kevin. In this and Home Alone 2, which is my personal favourite, he is cute and self-assured. Alex D Linz gives a spirited performance in Home Alone 3, but Michael Weinburg just doesn`t do anything with the script(which was terrible), other than whine in the fourth film. Anyway back to Home Alone. Joe Pesci and Daniel Stern steal the film, with their goofiness and charm that was evidently missed in the last two instalments. Matching them, is the late great John Candy, and here he is wonderful. Candy has starred in movies like Uncle Buck and Planes, Trains and Automobiles, both of which are hilarious. Home Alone just broadens the comedic talent, that Candy certainly had. The film looks beautiful, with very good direction, and best of all great visual jokes and traps, as well as a fun and sometimes touching script. My problem is why is the rating for both Home Alone and Home 2 so low, when almost everyone I know consider them as holiday classics? All in all, a funny, touching and underrated film, that could have been a little shorter(only by one or two minutes). 9/10 Bethany Cox', 'UniqueParticle', '203c2490-f370-4684-a7cd-7290ceeddae0',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('026f3005-81a9-446f-8824-f7a406928390', 9, 'But don`t forget about the presence of Stern and Pesci as bumbling comedic antagonists as Culkin is Kevin. As he is sent to his room after his jerk of a brother blames him for a mistake.

And that Kevin is left behind after the family were trying to make it to France there. But at first he loves having the house to himself, eats pizza, and does things that he would not have to do.

But when he misses his family there. After an old man played by the late Roberts Blossom there is meant to be scary but in reality he is a kind old man just misunderstood there.

He has to protect the house while trying to get his family back home. Really a good start in MacCulay Culkin`s career.', 'MovieAddict2016', '203c2490-f370-4684-a7cd-7290ceeddae0',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('b137cee8-544d-4e21-8cc8-d914bbbe730b', 10, 'I like the bit when he slaps on aftershave and then screams.', 'Doylenf', '203c2490-f370-4684-a7cd-7290ceeddae0',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('adcf1acd-521a-4343-97f1-46d40604a113', 7, 'This type of family comedy truthfully works better if you are grown up with the stooges. Because this film has a climactic scene with more slapstick than most can take. I can though. But if you think this is strictly a kids film, parents will like it too I bet. The plot follows a kid (Macaulay Kulkin) who gets left behind in a Chicago suburb while his family leaves for Paris. And though the house is all his, 2 burglars (Joe Pesci and Daniel Stern who give the best on-screen duo of 1990) want the house. But not without the climax. While most of the film is unbelievable (both good and bad), most of the film should keep families in good spirits, unless parents don`t enjoy seeing Pesci getting his head on fire and Stern screaming like a girl. Funny, even if it`s not John Hughes` (writer/producer here) best. B+', 'tfrizzel', '203c2490-f370-4684-a7cd-7290ceeddae0',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));

-- Harry Potter
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('af13c565-1996-444b-ab9c-ec7daf681cb9', 10, 'Once upon a time (and not that long ago), in the vivid, fertile imagination of author J.K. Rowling, a character was born: A boy. A young boy named Harry, who was destined to become one of the most beloved characters to emerge from a work of fiction in a long, long time, and was quickly embraced by young and old alike in all corners of the world. And now, thanks to the magic of the cinema, Harry and his companions fairly leap from the pages of the novel to the silver screen in the phenomenal motion picture, `Harry Potter and the Sorcerer`s Stone,` directed by Chris Columbus and written for the screen by Steve Kloves. Indeed, Harry Potter is a boy, but not just any boy; because Harry (Daniel Radcliffe) just happens to be a wizard. But, orphaned as a baby, Harry has been raised by his Aunt Petunia (Fiona Shaw) and Uncle Vernon Dursley (Richard Griffiths), who never let him in on the fact that he was, well-- what he was. It seems that Petunia didn`t approve of her own sister-- Harry`s mother-- because she was a witch; nor of Harry`s father because he, too, was a wizard. When Harry turns eleven, however, the secret is out of the bag when-- after some strange goings-on-- a giant of a man named Rubeus Hagrid (Robbie Coltrane) shows up at the Dursley`s door to collect Harry and take him off to `Hogwarts,` a school for wizards and witches and all who would perfect the gift with which they were born: The gift of magic! And from the moment Harry boards the train (from station platform nine-and-three-quarters) that will take him to his destiny, the magic is alive-- for Harry, and for the audience, as well; and it`s a journey you will never forget.

What a monumental undertaking to even think of attempting-- translating and transferring this passionately beloved work from novel to the screen. Because to millions of people, Harry and his companions are so much more than merely characters in a book; these are characters for whom people have made a special place in their hearts, which puts a great burden of trust upon the man who would attempt to bring them to life. And Chris Columbus, it turns out, was the right man for the job. More than rising to the occasion and with some magic of his own-- and a lot of help from an extraordinarily talented cast and crew-- Columbus has delivered a film that is not only true to the story, but true to the very spirit that makes Harry Potter so special. The special effects are absolutely beyond astounding, and Columbus, with a keen eye for detail and without missing a beat, keeps it all on track and moving right along at a pace and with a sense of timing that makes this an absorbing, thoroughly entertaining and enjoyable experience from beginning to end. From the opening frame you get the feeling that you`re about to have a singular experience; and you`re right. Because you`ve just entered the world of Harry Potter. And it`s magic.

Even having the best special effects do not a great movie make, however, and this film is no exception; what catapults this one to the top are the performances, beginning with Radcliffe, whom you quickly forget is an actor playing a part. And that about sums up what kind of a job this young man does here. Without question, he IS Harry Potter, physically and emotionally, and when he waves his wand and does what he does, you believe it. A wonderful performance by a gifted actor who has a great career ahead of him; without question the perfect choice for the role of Harry.

Also turning in excellent performances are Rupert Grint as Ron Weasley, and Emma Watson as Hermione. As with Radcliffe, the casting here could not have been more perfect. Grint is `Everyboy,` with that special glint in his eye and a manner that makes him especially endearing. And the spunky Watson adds some real sparkle to the film as Hermione, the one with the sense of urgency and the wherewithal to get things done; a real role model for young girls everywhere.

It`s obvious that a lot of care went into the casting of this film, and it`s a big part of why it is so successful. Richard Harris, as Headmaster Albus Dumbledore; Maggie Smith as Professor McGonagall; John Hurt as Mr. Ollivander; Ian Hart as Professor Quirrell. Exceptional performances from one and all, with two that stand out as especially memorable: Robbie Coltrane, who readily conveys the fact that Hagrid`s heart is of a size that matches that of the man; and Alan Rickman, as Professor Severus Snape, deliciously droll while demonstrating menace through the fine art of articulation.

The additional supporting cast includes John Cleese (Nearly Headless Nick), Warwick Davis (Professor Flitwick), Julie Walters (Mrs. Weasley), Zoe Wanamaker (Madame Hooch), Tom Felton (Draco Malfoy), Harry Melling (Dudley) and David Bradley (Filch). From Rowling`s imagination to the written page to real life (albeit via the movie screen), `Harry Potter and the Sorcerer`s Stone` is a triumph many times over; a unique film of truly universal appeal, the likes of which is as rare as, well-- a sorcerer`s stone. A film in which adults and children alike will rejoice, because it speaks to the heart in a universal language of life, love, experience and imagination; a film that states unequivocally that magic exists-- as long as there`s a single child with a single dream somewhere in the world, and real wizards like J.K. Rowling, Chris Columbus, Steve Kloves and every member of this wonderful cast and crew around to bring it to life as they have here. An instant classic in every sense of the word, this is truly a film for the ages. A remarkable achievement, this IS the magic of the movies. I rate this one 10/10.', 'HotToastyRag', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('ec23ced1-b02d-42fa-a87f-391801dd2b8b', 8, 'Having read the first few Harry Potter books before 2001 and hearing about the hype for the first movie, I was excited. I heard there was going to be an all-British cast (which makes sense, right?) and we`d get to see a live version of one of the defining novels of our generation. From what I remember I went with my family and a family friend to see the movie the day after Christmas and was pleasantly amazed. After the movie was over, I watched the credits and discovered some familiar names (the late Alan Rickman, Sister Act`s Maggie Smith, James Bond 007`s Robbie Coltrane, and Star Wars` Warwick Davis, others not so familiar (the kids, some of whom had their debut). But it was a good movie and was a party of colors and sights for all to see. This is easily my favorite of all the Harry Potter films. The catalyst of the movie series!', 'Cool-Lion14', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('9f2a05cc-9ea1-43a4-9df6-fdc54dfdad50', 7, 'I enjoyed this movie immensely. But, like "The Phantom Menace," I`ve had a very hard time viewing it objectively. There was so much anticipation leading up to its release, I simply enjoyed the experience of being there. Having read all four books in the series a few times each, I am overly familiar with the events in the story. As I watched the movie, my continuing thought was "How well will the next part of the story be translated to the screen?" rather than "How entertaining is this film overall?" I have trouble answering the latter question because I was already entertained by watching a wonderful story dramatized, so I`ll never know how I`d have reacted had I seen this movie without having read the books.

Critics talk about how incredibly faithful the movie is to the book, and perhaps I`d have had an easier time detaching the two in my mind had the movie set off on its own course. Indeed, many classic children`s movies, like "The Wizard of Oz" and "Mary Poppins," are so successful partly because they`re so different from the books that inspired them. But these are exceptions; in my experience, most children`s movies reveal their weaknesses in how they diverge from the books upon which they`re based. And much of what makes the Harry Potter phenomenon unique is that it is the first time in ages that a children`s book, without a movie accompanying it, has generated this much popularity. According to an article I read a year ago, the universe of Harry Potter has become as real in the minds of youngsters and adults as that of a popular movie series like Star Wars. Therefore, it will be very hard for any film based upon it to compete with it. In the minds of die-hard fans, any changes made to the story will be seen as desecrating the fantasy world that Rowling created. That`s why it`s easy to understand why the filmmakers were so reluctant to change anything.

As a faithful rendering of the book squeezed into a two-and-a-half hour period, the movie is beautifully done. I don`t have a single complaint about any of the actors, who successfully bring to life, with the aid of costume design and special effects, the many colorful characters from the book. My favorite character, the giant Hagrid, is played by Robbie Coltrane, and I say with no exaggeration that he is exactly how I imagined him while reading the book. It`s as if they took the image in my mind and transferred it to the screen. While I had my own personal image of Snape (for some reason, I always imagined him as the head villain from another Chris Columbus film, "Adventures in Babysitting"), Alan Rickman is perfect in the role. I usually expect to have words of criticism for some performances, but I just don`t. The remaining adult actors, including Maggie Smith as Professor McGonagall and Richard Harris as Albus Dumbledore, are as good as they possibly could be, and the kids do an excellent job of holding their own against these veterans. Some have criticized Daniel Radcliffe for appearing too subdued in the title role, but that`s exactly how the character is portrayed in the book: modest, unassuming, and laid-back. The kids who play Harry`s two best friends are flawless.

I had a lot of worries about the fact that it was being directed by Chris Columbus, whose entire directorial career so far has consisted of over-the-top slapstick films. I was pleasantly surprised that he did not direct the Harry Potter film in this way. Except for brief moments like the children`s delayed reaction to a giant three-headed dog they encounter and Harry`s swallowing the quaffle ball, there is nothing here to remind us that this film is directed by the same person who gave us films like "Home Alone" and "Mrs. Doubtfire." Indeed, I think Columbus may have gone just a tad bit too far in trying not to make the film seem cartoony. I would have liked to see a little more emotion on the actors` faces at certain times. Overall, however, his restraint works nicely in giving the film the kind of believability the book possesses.

But much is left out. Harry`s caretaker Uncle Vernon, a prominent character in the book, is given less attention in the movie than some of the bit characters. The gently satirical aspects of Hogwarts School aren`t in the movie at all. We never see the ghostly history teacher who died several years back but kept on teaching. Lines like the following--"Professor McGonagall watched [her students] turn a mouse into a snuffbox--points were given for how pretty the snuffbox was, but taken away if it had whiskers"--find no equivalent in the movie. The movie does include platform nine-and-three-quarters, though the way the kids disappear into the wall isn`t as mysterious as I had visualized, and the sorting hat is there, minus the great poem explaining the differences between the four schools.

Not that I`m blaming the movie for omitting some details. Some things from the book would not have translated easily to the screen, and it would have been very difficult to stick everything in. Had Columbus done so and allowed the film to be as long as necessary (eight hours, maybe?), like a BBC miniseries, the film might have been a masterpiece, but few kids would ever have had the patience or attention span to sit through it.

The problem is that the amusing details are much of what make Harry Potter such a special story. A whole universe is created in Rowling`s series, in which a magical society exists within our own ordinary "muggle" world and is kept secret by a bureaucracy with its own rules, history and politics. The way magic is treated in her books, not as something medieval but as very similar to the way our own contemporary world works, is a large part of their charm. Take away these details, and you`re left with a fairly conventional tale of a young wizard fighting an evil sorcerer.

Although the audience I was with broke into applause as soon as the movie ended (something I`ve never seen happen before, though I don`t go to the theater that often), some people have complained about the movie dragging at certain points. I didn`t have that problem, but, as I said, I wasn`t really trying to get involved in the movie`s story. After thinking about it, it does seem like parts of the movie fail to convey a sense of urgency. Why should this be? I never felt that way when reading the books, and this is without a doubt the very same story.

The answer, I think, is that the books portray much of Harry`s anxiety in trying to succeed in school (for if he`s kicked out, he`ll go straight back to his horrible uncle) and fit in with the kids there. The movie doesn`t tap into these anxieties enough, so why should we care whether he wins the Quidditch match (other than that he survives in one piece) and gets through the school year? The only real suspense in the movie after he arrives at Hogwarts comes from the story of Lord Voldemort returning, which in the book is almost secondary. Harry`s adventures getting along in the school are fun and interesting, but as they are presented to us in the film, there isn`t enough tying them all together.

What we have here is a serviceable dramatization of a wonderful children`s series, but it doesn`t entirely succeed in standing on its own. Perhaps it should have diverged from the book just a little, to compensate for the difficulties in translating some of the book`s delights to the screen. In its current form, it`s almost like a preview of the book. Its lack of fullness, and its dependence on the book, might actually increase the popularity and endurance of Rowling`s series by making those who see the film yearn for more, which they can get from the real thing.', 'jhclues', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('79cb11d9-6c4d-49f8-b1c5-5afbe7d91235', 8, 'Like a lot of others, I refused to watch this film when it was originally released, thinking it was going to be another movie for kids, loosely taken from the source. Was I ever wrong?

J.K. Rowling`s novel was brilliantly taken from book to screen. The acting, directing and especially the special effects were tremendously awesome. Director Chris Columbus did a superb job with the direction, I was surprised he didn`t get an Academy Award nomination. The acting was too, excellent, especially from the experienced actors like Alan Rickman playing Severus Snape. Truly one of his best performances.

A great adaptation of a very popular book, a fine example of cinema.', 'Hollywood_Yoda', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('19e5ccf1-ccbe-43f8-9128-a897a268316e', 7, 'I really liked this film, but I much prefer the book, which has a lot more magic and wonder. Daniel Radcliffe is very likable as Harry, and he is given solid support by a funny Rupert Grint and a good Emma Watson, though she was annoying at times. The scene stealer was definitely Robbie Coltrane; I actually can`t imagine anyone else playing Hagrid, Coltrane was just hilarious. Alan Rickman and Maggie Smith were also great, but for me the standout was the late Richard Harris. Now I much prefer Harris`s interpretation of Dumbledore. He was soft-spoken, and actually fitted the part better. Both of these qualities were lost in the interpretation that Michael Gambon gave. I am not saying that Michael Gambon was bad, he just wasn`t my ideal choice for Harris`s replacement. The film is fairly faithful to its source material, and looks very beautiful. However, it is a bit long, and very young children may find Voldemort too frightening. I know because I have triplet brother and sisters who saw it, and couldn`t sleep for about a month after viewing. In conclusion, a very good film, well performed and quite dark. 8/10 Bethany Cox', 'AvinashPatalay', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('f28b0617-525c-486b-b517-fafb20458450', 8, 'in 2001, in the film Harry Potter and the Sorcerer`s Stone, began one of the best sagas of all time, based on the book of the same name by JK Rowling, the film hit full in the cast, all actors are great in their characters, Daniel Radcliffe this impeccable as Harry Potter, the resemblance is too large, Rupert Grint this great as Ron Weasley, Emma excellent Watson as Hermione Granger, Robbie Coltrane as Hagrid, Richard Harris as Dumbledore (which unfortunately from the third movie substituted series, having deceased), Maggie Smith, Alan Rickman great as Snape, Ian Hart, Tom Felton, and etc, all goods, the special effects are great, the picture is great, especially the castles, the soundtrack is very good, and full of great moments, as the final, obvious that the movie has errors, the script has some problems, and the film is very long, I think it was longer than it should, and the film is faithful to the book, even with some missing characters, Harry Potter and the Sorcerer`s Stone is a very good film, and marks the beginning of the saga of the Wizard in the movies. Note 8.2', 'stormhawk2021', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('bf15090c-1d26-4c63-9a8f-183021ee614d', 9, 'During my childhood, the earlier Harry Potter books got me into the franchise and especially Fantasy Literature in general. They had thought provoking writing, likeable characters, and compelling world building. Then I saw this movie adaptation of The Sorcerer`s Stone (The Philosopher`s Stone in the UK) back in theaters and loved it. It`s not a perfect film I`ll admit, but it`s a very good start to a successful fantasy movie franchise.

Sure, it`s a bit overlong and the child performances from Daniel Radcliffe, Rupert Grint and Emma Watson, while not terrible by any means, could have used some fixing though they did get better as the later movies progressed.

Everything else still holds up. The visual effects/cinematography are beautiful to look at, the directing from Chris Columbus is great, the make up designs are well built, and the music score from John Williams is enchanting and haunting especially Hedwig`s Theme. Not to mention the supporting actors are great with Robbie Coltrane as Harris and the late actors Alan Rickman and Richard Harris as Severus Snape and Professor Dumbledore.

Overall, Harry Potter and the Sorcerer`s Stone isn`t perfect but it`s a very good start to the successful fantasy movie franchise after 20 years. Recommended! :)', 'tfrizzel', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('b1967b9a-2b6c-491f-8bd7-1d4316310250', 10, 'When I first saw this movie I was ten years old, the same age the characters where supposed to be. My older cousin and her boyfriend took me to the Mall to watch a movie. Back then I wasn`t going very often to the cinema, due to the fact that my parents didn`t have time and I wasn`t old enough to go alone to any theater. The movie captivated my attention like nothing before and I became so interested in anything that had to do with this movie, and I heard that it was made after a book. I didn`t had Internet back then, but I found the first book at a library and convinced my mother to buy it. That`s how I became obsessed with reading and writing.

I may say, "Harry Potter" affected me in a positive way, because after I finished reading all the published books back then, I wanted to read more books and I must thank J.K.Rowling for her genius, if it wasn`t for her books, I might have been right now an average seventeen year old, at some party, drinking my brains out. This movie got me to the right path in life.

I know, you probably don`t care about my story, you readers only want to hear about what I thought of the movie, but I believe my story can influence you if you are a parent and thinking whether or not you should let your children watch this film. My advice is yes and I have presented my reason above.

The story is simply magical and "Hogwarts" is a genius invention. The movie is done well, almost perfect. It`s the closest to the book they can get and it`s an amazing experience for any kid.', 'kylopod', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('9f7c573e-6405-40db-8856-b5e330aa1585', 10, 'We live in a world where economics is hard. This forces practical limitations when making a movie. Time and money are sadly finite, cinema owners need to be pleased as well as fans and computer animation ain`t perfect. Given these limitations, this film is about as close to human perfection as it is possible to achieve. However, it`s extremely clear what an immense challenge it is to turn Philosopher`s Stone from book to film.

Two and a half hours is not long to explore a wonderful, magical world. Furthermore, the directors have bowed to the inevitable temptation to show us things that cannot be communicated so effectively in a book. The consequence is the feeling of a slightly breathless sprint in places.

It also means that the movie has to stay true to the spirit of the book rather than to the letter of it. There are omissions and there are changes. The changes that were made capture and maintain the spirit of the story really well; indeed, there are places where the story is more clearly and straightforwardly told in the movie than in the book. Some aspects of the story are fleshed out on screen and the additions are delightful, completely in keeping with the flavour of the world.

The humour of the movie is inevitably more visual than that of the book; no belly laughs, but a lot of smiles. Some punchlines have changed, but the reasons why the jokes are funny remain the same. Not knowing exactly what`s coming next is a good thing! It`s all kept tasteful, classy and above the belt; there`s nothing to cringe about.

The voice acting is almost uniformly brilliant. However, there are occasions where some of the actors are required to convey high emotions and are only given a second or two of face shot, or head-and-shoulders shot, to do so. This isn`t as much freedom as they need and they fall a little short. The blame here must fall on the decision to give the actors too much to do too quickly, not on the actors themselves.

Other than these rare jarring instances, the physical acting is frequently excellent and seldom less than completely adequate, judged against the highest of targets set by the book`s clear emotion descriptions.

Dan Radcliffe has the look, the mannerisms and the charm of Harry down pat. His strongest expressions are the bemusement that must be inherent at entering a world where science does not rule alone and the bravery that Harry shows in his achievements. Emma Watson possibly slightly overplays Hermione, but does so in a fully endearing fashion. There`s one scene which gives her too little chance to truly express panic; otherwise her performance needs no changes.

Rupert Grint has comic timing way beyond his years, hitting Ron`s lines perfectly. Tom Felton makes a stylish Draco; Matt Lewis` Neville character suffers from the acceleration, so the finale does come as a slight characterisation shock.

The Phelps brothers` Fred and George are distinctively cheeky rather than proactive pranksters; Chris Rankin imbues Percy with genuine authority. Sean Biggerstaff shines; his Oliver Wood is likeable and an ideal Quidditch team captain.

Robbie Coltrane`s Hagrid is the single dominant adult character, with maximum laughs extracted at every step. The movie changes strongly exaggerate one side of Hagrid`s nature, though; probably inevitable considering how much plot exposition his character has.

David Bradley has a vicious Argus Filch; John Hurt`s Ollivander is an eccentric treat, giving a wonderful introduction to the Wizarding World. The professors are uniformly excellent, though Richard Harris` Dumbledore comes off as disappointingly flat until the end.

The most ambitious point of the movie is the computer generated imagery. The stills are wonderful, but the fastest animation is restricted by the limitations of real-world technology. The book makes extremely stringent demands of the CGI; sometimes their overall effect in the movie is merely good rather than insanely great. Some of the magic spells and effects look awesome; others don`t capture the imagination nearly so much.

The world cannot yet completely convincingly animate human beings doing inhuman things, which serves as a clear reminder that you need fictional magic to make the impossible possible. The Quidditch scene is the most demanding of them all; while the sequence is action-packed and good-looking, disappointingly, it`s not a total success. Perhaps some of the scenes would have been better with more conventional special effects? (For instance, the lower-tech-looking Sorting Hat scene is one of the most delightful of them all.)

The set looks gorgeous. However, it may not stand up to detailed analysis. It`s fairly obvious that things are shot in many disparate locations, rather than one big Hogwarts School near Hogsmeade.

The score is absolutely wonderful. The soundtrack may rely too heavily on The Famous Bit, but it`s clear that the balance and mixture of things in the finished movie are exactly right.

The feel of the whole movie is everything fans could have hoped for. The dialogue is intensely measured, the colouring is suitably epic, the selection of what to leave in is really tightly considered. You get chills in your spine at the right places; you feel the triumphs as all-encompassing endorphin highs. It`s clear that the production have thought long, hard and lovingly. They are true fans of the story, they are the right people for the job, it all bodes very well for the second film.

So it could never have been the film that the hyper-literalists were hoping for, then, but it is as good as the practicalities of the real world could possibly permit. Don`t expect miracles and you`ll love it. I look forward to watching it again and again.', 'TheLittleSongbird', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('0604a617-537d-4d5e-a4de-1562100c3914', 9, 'This movie captures most aspects of the book perfectly. Being the first in the franchise, it has to do a lot of world building. But the writers and the director of this movie managed to keep things simple and to the point.

The cast is also perfect. All the younger actors were good enough and they keep improving with each movie. The older cast was amazing in their roles and help the movie feel more real. The music of John Williams was a masterpiece and added to the magical nature of the story.

Even after 2 decades, this movie still feels magical and captures the attention of many young and old audience.', 'miguelneto-74936', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
INSERT INTO public.comments(id, mark, review, username, film_id, wrote_at) VALUES ('2a500085-6367-4da8-870c-ece61d0ed788', 10, 'I watched all Harry Potter movies when I was 7 years old. After five years I watched the movies again at 12 years old and I feel this saga a classic, well, it is a classic. I started reading the first book like one day ago. Which my mom gave to me when I was a little kid. I like Harry Potter a lot and I would watch all the saga again', 'AnishMisra', '4108bc1f-cc23-422c-babd-3e19be79ac05',
                                                                                   TIMESTAMP '2023-06-13 00:00:00' + random() * (TIMESTAMP '2023-06-20 23:59:59' - TIMESTAMP '2023-06-13 00:00:00'));
